// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WineApp.Data;

#nullable disable

namespace WineApp.Migrations
{
    [DbContext(typeof(WineAppDbContext))]
    partial class WineAppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("WineApp.Models.TodoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TodoItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCompleted = false,
                            Name = "Prepare wine samples for tasting"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2024, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCompleted = false,
                            Name = "Review judge assignments"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DueDate = new DateTime(2024, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCompleted = false,
                            Name = "Compile final wine ratings report"
                        });
                });

            modelBuilder.Entity("WineApp.Models.Wine", b =>
                {
                    b.Property<int>("WineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Class")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Group")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("RatingName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("WineProducerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("WineId");

                    b.ToTable("Wines");

                    b.HasData(
                        new
                        {
                            WineId = 1,
                            Category = 3,
                            Class = 1,
                            Group = 0,
                            Name = "Polets røde",
                            RatingName = "Hemmelig Polets Røde",
                            WineProducerId = 1
                        },
                        new
                        {
                            WineId = 2,
                            Category = 3,
                            Class = 0,
                            Group = 2,
                            Name = "Polets andre røde",
                            RatingName = "Hemmelig Andre Polets Røde",
                            WineProducerId = 1
                        },
                        new
                        {
                            WineId = 3,
                            Category = 3,
                            Class = 0,
                            Group = 1,
                            Name = "Polets røde",
                            RatingName = "Hemmelig Tredje Polets Røde",
                            WineProducerId = 2
                        });
                });

            modelBuilder.Entity("WineApp.Models.WineProducer", b =>
                {
                    b.Property<int>("WineProducerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("OrganisationNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponsibleProducerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("WineyardName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Zip")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("WineProducerId");

                    b.ToTable("WineProducers");

                    b.HasData(
                        new
                        {
                            WineProducerId = 1,
                            Address = "Test adresse 21",
                            City = "Oslo",
                            Country = "Norway",
                            Email = "bestWines@fluffy.com",
                            OrganisationNumber = "111122223333445",
                            ResponsibleProducerName = "Test Testersen",
                            WineyardName = "Oslo Vest Wines AS",
                            Zip = "0125"
                        },
                        new
                        {
                            WineProducerId = 2,
                            Address = "Test adresse Ny 15",
                            City = "Grimstad",
                            Country = "Norway",
                            Email = "bestWinesEver@fluffier.com",
                            OrganisationNumber = "111122234567890",
                            ResponsibleProducerName = "Petter Testeren",
                            WineyardName = "Grimstad Vin og Vann AS",
                            Zip = "4525"
                        },
                        new
                        {
                            WineProducerId = 3,
                            Address = "Agder Alle 21",
                            City = "Kristiansand",
                            Country = "Norway",
                            Email = "bardeh@gmail.com",
                            OrganisationNumber = "222222223333445",
                            ResponsibleProducerName = "Bård Eik",
                            WineyardName = "Tech Wine AS",
                            Zip = "4631"
                        });
                });

            modelBuilder.Entity("WineApp.Models.WineRating", b =>
                {
                    b.Property<int>("WineRatingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("JudgeId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Nose")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Taste")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Visuality")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WineId")
                        .HasColumnType("INTEGER");

                    b.HasKey("WineRatingId");

                    b.ToTable("WineRatings");

                    b.HasData(
                        new
                        {
                            WineRatingId = 1,
                            JudgeId = "Hans",
                            Nose = 4,
                            Taste = 5,
                            Visuality = 5,
                            WineId = 1
                        },
                        new
                        {
                            WineRatingId = 2,
                            JudgeId = "Petter",
                            Nose = 3,
                            Taste = 4,
                            Visuality = 3,
                            WineId = 1
                        },
                        new
                        {
                            WineRatingId = 3,
                            JudgeId = "Frans",
                            Nose = 5,
                            Taste = 4,
                            Visuality = 6,
                            WineId = 1
                        },
                        new
                        {
                            WineRatingId = 4,
                            JudgeId = "Ola",
                            Nose = 5,
                            Taste = 4,
                            Visuality = 4,
                            WineId = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
