# fly.toml app configuration file generated for wine-rating-system on 2026-03-02T15:06:39+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'wine-rating-system'
primary_region = 'ams'

[build]
  dockerfile = 'Dockerfile'

[env]
  ASPNETCORE_ENVIRONMENT = 'Production'
  DataProtection__KeysPath = '/data/protection-keys'
  ForwardedHeaders__TrustAllProxies = 'true'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1

  [[http_service.http_options.replay_cache]]
    path_prefix = "/_blazor"
    ttl_seconds = 300
    type = "cookie"
    name = "__Host-WineApp.Auth"

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 100
    soft_limit = 80

  [[http_service.checks]]
    grace_period = '10s'
    interval = '15s'
    method = 'GET'
    path = '/health'
    protocol = 'http'
    timeout = '5s'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'

[[mounts]]
  source = 'data'
  destination = '/data'
  initial_size = '1gb'
